language: java

jdk: oraclejdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libfuse-dev fuse libssl-dev libattr1-dev make cmake automake python

before_script:
  - TEST_DIR="/tmp/xtreemfs_xtestenv"
  - XTREEMFS_DIR=`pwd`

script:
  - make server
  - BUILD_CLIENT_TESTS=true make client_debug
  - ./tests/xtestenv --clean-test-dir -x $XTREEMFS_DIR -t $TEST_DIR -c $XTREEMFS_DIR/tests/test_config.py travis

after_failure:
  - JUNIT_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'JUnit tests'`
  - CPP_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'C++ Unit tests'`
  - if [ $JUNIT_RESULT = "false" ]; then cat $TEST_DIR/log/junit.log; fi
  - if [ $CPP_RESULT = "false" ]; then cat cpp/build/Testing/Temporary/LastTest.log; fi

